[features]
seeds = false
skip-lint = false
[programs.localnet]
final_project = "8PfXMVu3wzJJnAu1bZxML5aAounkcEQctFbtD4xYS5Mn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/last_vondert/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
